Purchase
SharmaTraders/backend pull request #13
Opened 2024-05-14 19:19 UTC by himal28924

2024-05-14 21:09 UTC, MrSachin7 requested changes

2024-05-14 21:09 UTC, MrSachin7 commented on Tests/UnitTests/Domain/purchase/InvoiceNumberTest.cs
> +    [Theory]
plural naming again...

2024-05-14 21:09 UTC, MrSachin7 commented on Tests/UnitTests/Factory/ValidObjects.cs
> +{
the class here makes more sense to be static

2024-05-14 21:09 UTC, MrSachin7 commented on src/Application/CommandHandlers/purchase/AddPurchaseHandler.cs
> +        }
maybe you did consider this but the estimatedPricePerKilo of an item is equal to the latest added stock's expectedValuePerKilo. 
When we set the expectedValuePerKilo = purchase.UnitPrice we then will also update the item's estimatedPricePerKilo.
I am not sure if this is the expected behaviour because i assume you can sell in slightly less value for your regular customers. But again , its called "EXPECTED" value per kilo for a reason. Maybe give this a thought if you havent already.

2024-05-14 21:09 UTC, MrSachin7 commented on src/Domain/Entity/BillingPartyEntity.cs
>              throw new DomainValidationException("OpeningBalance", ErrorCode.BadRequest,
I am not sure if it should be  "OpeningBalance" for updating balance at least.

2024-05-14 21:09 UTC, MrSachin7 commented on src/Domain/Entity/PurchaseEntity.cs
> +
Dont we already have a common error messange for invalid date ? Or do purchase expect different format ?

2024-05-14 21:09 UTC, MrSachin7 commented on src/Domain/Entity/PurchaseEntity.cs
> +    }
Okay, maybe you need to explain whats going on here. What is ValidationContext ??

2024-05-14 21:09 UTC, MrSachin7 commented on src/Domain/Entity/PurchaseEntity.cs
> +    }
Please dont consider me being too nifty, but null checks are advised to be done as value is null // value is not null

2024-05-14 21:09 UTC, MrSachin7 commented on src/Domain/Entity/PurchaseEntity.cs
Regarding these required fields, if only place they work from is WebApi, I dont think they are necessary. Keep them if you think they provide value to us.

2024-05-14 21:09 UTC, MrSachin7 commented on Tests/IntegrationTests/Purchase/AddPurchaseTest.cs
> +    }
Tests name are plural ??, usually at least

2024-05-14 21:09 UTC, MrSachin7 commented on src/Domain/Entity/PurchaseLineItem.cs
> +            }
I would prefer this in their own methods.

2024-05-14 21:09 UTC, MrSachin7 commented on src/Domain/Entity/PurchaseLineItem.cs
> +            }
I would prefer this in their own methods.

2024-05-14 21:09 UTC, MrSachin7 commented on src/Domain/Entity/PurchaseLineItem.cs
> +            }
I would prefer this in their own methods.

2024-05-14 21:09 UTC, MrSachin7 commented on src/Tools/ErrorMessages.cs
> +    public const string PurchaseEntityDateFormatInvalid = "Invalid date format. Expected format is YYYY-MM-DD.";
This already exists in the common one.

2024-05-14 21:09 UTC, MrSachin7 commented on src/Tools/ErrorMessages.cs
> +    public const string PurchaseEntityInvalidPurchaseLineItem = "Invalid purchase line item.";
This is very vague , what is invalid, is it itemname? , is it amount  ?

2024-05-14 21:09 UTC, MrSachin7 commented on src/Tools/ErrorMessages.cs
>      }
I would move this up so it sits together with billing parties

2024-05-14 21:11 UTC, MrSachin7 commented on src/Domain/Entity/PurchaseEntity.cs
> +    }
I now realize what you are doing here. 
But the sole fact that lineItems EXISTS MEANS they are valid. 
That is the whole idea of domain driven design.

If they were invalid, that would have already thrown exception where they were created.

2024-05-15 10:44 UTC, MrSachin7 commented on src/Domain/Entity/PurchaseLineItem.cs
The required properties must be public required Type name ; SO that nobody creates an invalid entity

2024-05-15 13:52 UTC, himal28924 commented on src/Application/CommandHandlers/purchase/AddPurchaseHandler.cs
> +        }
When i was doing it : I simply thought the ExpectedValuePerKilo will be the value of latest transaction

2024-05-15 14:02 UTC, MrSachin7 commented on src/Application/CommandHandlers/purchase/AddPurchaseHandler.cs
> +        }
Yes it is, i just need to be sure that this is the expected behaviour

2024-05-15 15:13 UTC, himal28924 commented
Ready for review AGAIN

2024-05-15 15:56 UTC, MrSachin7 approved these changes
Looks good to me ✌️✌️. I didnt deep dive into the tests, hope they are correct.

2024-05-15 16:22 UTC, merged